cmake_minimum_required(VERSION 3.16)
project(SVSComputeConsumer LANGUAGES CXX)
if(NOT TARGET SVSSDK::SDK)
	find_package(SVSSDK CONFIG REQUIRED)
endif()
add_executable(SVSComputeConsumer main.cpp)
target_compile_features(SVSComputeConsumer PRIVATE cxx_std_17)
target_compile_definitions(SVSComputeConsumer PRIVATE NOMINMAX)
target_link_libraries(SVSComputeConsumer PRIVATE SVSSDK::SDK ${CMAKE_DL_LIBS})
install(TARGETS SVSComputeConsumer RUNTIME DESTINATION bin)
